[package]
name = "fx2la"
description = "Driver for FX2-based fx2lafw logic analyzers with nusb"
license = "MIT OR Apache-2.0"
repository = "https://github.com/kevinmehall/nusb-fx2la"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-lite = "2.6.1"
log = "0.4.28"
nusb = { version = "0.2.7", features = ["smol"] }
thiserror = "2.0.17"

[target.'cfg(any(unix, windows))'.dependencies]
async-fs = { version = "2.2.0", optional = true }
async-io = "2.6.0"

[target.wasm32-unknown-unknown.dependencies]
gloo-timers = { version = "0.4.0", features = ["futures"] }
gloo-net = { version = "0.7.0", default-features = false, features = ["http"], optional = true }

[features]
fs = ["dep:async-fs"]
web-fetch = ["dep:gloo-net"]
default = ["fs", "web-fetch"]

[dev-dependencies]
env_logger = "0.11.8"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
rustdoc-args = ["--cfg", "docsrs"]
